[package]
name = "tc-value"
version = "0.14.0"
edition = "2021"

[dependencies]
bytes = "1"
collate = { path = "../deps/collate" }
destream = { path = "../deps/destream", version = "0.10" }
get-size = "0.1"
hr-id = { path = "../deps/hr-id", version = "0.7" }
number-general = { path = "../deps/number-general", version = "0.14", default-features = false, features = ["stream"] }
pathlink = { path = "../deps/pathlink", default-features = false }
safecast = "0.2"
serde = { version = "1", features = ["derive", "rc"], optional = true }

[features]
serialize = [
    "dep:serde",
    "pathlink/serialize",
    "hr-id/serde",
    "number-general/serde",
]

[dev-dependencies]
destream_json = { path = "../deps/destream_json", version = "0.15", default-features = false }
futures = "0.3"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
